#pragma once

// Board settings
#define BOARD_WIDTH 10
#define BOARD_HEIGHT 20

// Tetromino controls
#define MOVE_SPEED 0.9f
#define DROP_SPEED 0.5f
#define DROP_SPEED_FAST 0.1f

// Keyboard
#define ROTATE_CLOCKWISE_KEY GLFW_KEY_UP
#define ROTATE_CCLOCKWISE_KEY GLFW_KEY_D
#define ROTATE_180_KEY GLFW_KEY_S
#define HARD_DROP_KEY GLFW_KEY_SPACE
#define SOFT_DROP_KEY GLFW_KEY_DOWN
#define MOVE_LEFT_KEY GLFW_KEY_LEFT
#define MOVE_RIGHT_KEY GLFW_KEY_RIGHT
#define SWAP_HOLD_PIECE_KEY GLFW_KEY_C

//
//#define ROTATE_CLOCKWISE_KEY GLFW_KEY_X
//#define ROTATE_CCLOCKWISE_KEY GLFW_KEY_Z
//#define ROTATE_180_KEY GLFW_KEY_UP
//#define HARD_DROP_KEY GLFW_KEY_SPACE
//#define SOFT_DROP_KEY GLFW_KEY_DOWN
//#define MOVE_LEFT_KEY GLFW_KEY_LEFT
//#define MOVE_RIGHT_KEY GLFW_KEY_RIGHT
//#define SWAP_HOLD_PIECE_KEY GLFW_KEY_LEFT_SHIFT
